#!/bin/bash

if [ ! -d $OPENSHIFT_NODEJS_DIR/node_modules/bower ]
then
    cd $OPENSHIFT_NODEJS_DIR
    npm install bower
fi

cd $OPENSHIFT_HOMEDIR/app-root/repo
HOME=$OPENSHIFT_REPO_DIR bower install
cd $OPENSHIFT_HOMEDIR